GENCCODE_ASSEMBLY_TYPE=
SO=
SOBJ=
A=a
LIBPREFIX=libs
LIB_EXT_ORDER=.56.1
COMPILE=arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -O2 -DPIXMAN_NO_TLS -I/home/easyrpg/3ds/portlibs/arm/include   -DU_ENABLE_DYLOAD=0 -DU_HAVE_ATOMIC=1 -DU_HAVE_MMAP=0 -DU_HAVE_POPEN=0  -DU_ATTRIBUTE_DEPRECATED= -march=armv6k -mtune=mpcore -mfloat-abi=hard -O2 -DPIXMAN_NO_TLS -I/home/easyrpg/3ds/portlibs/arm/include   -c
LIBFLAGS=-I/home/easyrpg/3ds/portlibs/arm/include  
GENLIB=arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -O2 -DPIXMAN_NO_TLS -I/home/easyrpg/3ds/portlibs/arm/include   -L/home/easyrpg/3ds/portlibs/arm/lib -L/home/easyrpg/3ds/libctru/lib  -shared 
LDICUDTFLAGS=
LD_SONAME=
RPATH_FLAGS=
BIR_LDFLAGS=
AR=arm-none-eabi-ar
ARFLAGS=r
RANLIB=arm-none-eabi-ranlib
INSTALL_CMD=/usr/bin/install -c
